runtime: php55
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /style.css
  static_files: style.css
  upload: style.css
- url: /img/(.*\.(gif|png|jpg))
  static_files: img/\1
  upload: images/(.*\.(gif|png|jpg))